### ISSUE TITLE
Is it possible to parse "multipath.conf" like this?

### ISSUE THREAD

**Issue by zhucan** [lytics/confl#12]
![image](https://user-images.githubusercontent.com/13997135/74031078-938f3680-49eb-11ea-9460-8871c9c6b66b.png)

Because map types cannot have the same key，is It possible to solve this conf?

**Comment by araddon** [comment]
I think you want this  
https://github.com/lytics/confl/blob/master/decode_test.go#L47

```go
package main

import (
	"fmt"

	"github.com/lytics/confl"
)

type DevicesConf struct {
	Devices []*Device
}
type Device struct {
	Vendor             string
	Product            string
	PathGroupingPolicy string `json:"path_grouping_policy"`
}

var confStr = `
devices [
	{
		Vendor: "vname"
		path_grouping_policy:  "pgp1"
	}
]
`

func main() {

	var config DevicesConf
	if _, err := confl.Decode(confStr, &config); err != nil {
		fmt.Println(err)
		return
	}

	for i, dev := range config.Devices {
		fmt.Printf("%d:  %+v\n", i, dev)
	}

}

```

**Comment by zhucan** [comment]
@araddon The format of the conf like this:

devices {
	device {
		vendor			"COMPAQ  "
		product			"HSV110 (C)COMPAQ"
		path_grouping_policy	multibus
		path_checker		readsector0
		path_selector		"round-robin 0"
		hardware_handler	"0"
		failback		15
		rr_weight		priorities
		no_path_retry		queue
	}
	device {
		vendor			"COMPAQ  "
		product			"MSA1000         "
		path_grouping_policy	multibus
	}
}

not like it :
var confStr = `
devices [
	{
		Vendor: "vname"
		path_grouping_policy:  "pgp1"
	}
]

**Comment by araddon** [comment]
I don't believe there is support for that as the keys "device" are not unique.   So, "maps"  aka 
```
devices {
     device  {
         vendor "compaq"
     }
}
```
This is saying that a map (map[string]interface{}) of devices will be mapped, but you will end up with one entry because they both have same key `device`

You might try:
```
devices {
    compaq {
        Vendor "compaq
        ...
    }
}
```
Where each key identifying entry is unique.   

Or else use arrays as in my example.   

I also found this similar one the other day 
https://github.com/hjson/hjson-go

**Comment by zhucan** [comment]
@araddon yes, it can only deal with the unique key in the config when use the map. Thnaks.
