### ISSUE TITLE
Maybe multi-line strings should remove common indent

### ISSUE THREAD

**Issue by tv42** [lytics/confl#3]
Perhaps this would make sense. I can see a lot of callers wanting this; I did.

Inspiration:
- https://github.com/MakeNowJust/heredoc
- https://github.com/renstrom/dedent

Be careful to preserve inner indentation. That is:

```
foo (
    # I am an embedded markdown article

    Blah blah.

        func code() {
            // code inside markdown is indented more
        }

)
```

Note that the `#` there is not a comment, it's inside the string literal (this is already current confl behavior).

**Comment by araddon** [comment]
good idea, got a pr up ill merge it in soon unless you want to comment.
